services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - arcade-backend/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./arcade-backend
    ports:
      - 5001:5000
    depends_on:
      - postgres
    env_file:
      - arcade-backend/.env

  web:
    container_name: web
    build: ./arcade-frontend/app
    volumes:
      - web-volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - web-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - web

volumes:
  postgres-volume:
  web-volume:
